name: containers (all branches)
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 12 * * *'

jobs:
  branch:
    secrets: inherit
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        fedora_branch: ['43']
    uses: ./.github/workflows/containers.yml
    with:
      fedora_branch: ${{ matrix.fedora_branch }}
